server:
  port: 5050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: 123456
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'